version: '2'
services:
    mrs_pilote-app:
        image: mrs_pilote
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mrs_pilote-mysql:3306/mrs_pilote?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mrs_pilote-mysql:
        extends:
            file: mysql.yml
            service: mrs_pilote-mysql
